// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package computing

import (
	"github.com/swanchain/computing-provider-v2/internal/db"
)

import (
	_ "unsafe"
)

// Injectors from wire.go:

func NewCpInfoService() CpInfoService {
	gormDB := db.NewDbService()
	cpInfoService := CpInfoService{
		DB: gormDB,
	}
	return cpInfoService
}
