import { useCallback, useMemo, useState } from 'react';
import { AlertCircle } from 'lucide-react';
import { api } from '../api/client';
import { usePolling } from '../hooks/usePolling';
import { OTHER_COLOUR, OTHER_LABEL, SERIES_COLOURS, buildModelColours, colourFor, type ModelColourMap } from '../lib/modelPalette';
import type { ModelEarnings, UsagePoint, UsageSource, UsageTotals } from '../types';

/**
 * What the GPUs did, by where the work came from.
 *
 * The earnings chart says what was paid. This says what was served, so the
 * difference — the operator's own benchmarks, the node's probes, and work that
 * reached a model server without passing through the node — is visible rather
 * than being load nobody can account for.
 *
 * Bars measure generated tokens by default: the one figure every source has
 * exactly, since direct usage comes from a server's counters, which count
 * tokens but not requests. Input tokens are the larger share of the work, so
 * they are a toggle away — with direct input shown as a floor, because the
 * server's prompt counter skips cache hits and the gap can only be larger.
 *
 * Two views of the same bars. By model is the default and uses the colours the
 * earnings chart below uses, so a model reads the same in both; by source is
 * how paid work is told apart from everything else.
 */

interface Series {
  key: string;
  label: string;
  colour: string;
  sources: UsageSource[];
  title: string;
}

// Colour carries meaning here, not identity: blue is the only paid series.
const SERIES: Series[] = [
  { key: 'hub', label: 'Hub (paid)', colour: SERIES_COLOURS[0], sources: ['hub'], title: 'Routed by Swan Inference — the only traffic that earns' },
  { key: 'local', label: 'Local gateway', colour: SERIES_COLOURS[1], sources: ['local'], title: 'Your own clients, sent through the node’s local gateway' },
  { key: 'direct', label: 'Direct to backend', colour: SERIES_COLOURS[2], sources: ['direct'], title: 'Generated by a model server without passing through the node' },
  { key: 'probes', label: 'Probes', colour: OTHER_COLOUR, sources: ['health', 'selfcheck'], title: 'This node’s own health and audit checks' },
];

const SOURCE_SHORT: Record<string, string> = {
  hub: 'hub',
  local: 'local',
  direct: 'direct',
  health: 'probes',
  selfcheck: 'probes',
};

/** Where a model's tokens came from, as "hub 12k · local 3k". */
type Metric = 'out' | 'in';

/** The figure a bar measures: generated tokens, or input tokens. */
function tokensOf(t: UsageTotals, metric: Metric) {
  return metric === 'out' ? t.tokens_out : t.tokens_in;
}

function sourceBreakdown(bySource: Partial<Record<UsageSource, UsageTotals>> | undefined, metric: Metric) {
  const acc = new Map<string, number>();
  for (const [src, t] of Object.entries(bySource ?? {})) {
    if (!t || tokensOf(t, metric) <= 0) continue;
    const k = SOURCE_SHORT[src] ?? src;
    acc.set(k, (acc.get(k) ?? 0) + tokensOf(t, metric));
  }
  // Direct input is a floor (the server's prompt counter skips cache hits).
  return [...acc].map(([k, v]) => `${k} ${metric === 'in' && k === 'direct' ? '≥' : ''}${formatTokens(v)}`).join(' · ');
}

interface Segment {
  key: string;
  label: string;
  colour: string;
  value: number;
  detail: string;
  title?: string;
}

type ModelsBySource = Record<string, Partial<Record<UsageSource, UsageTotals>>>;

/** Sum a point's (or the window's) per-model figures across sources. */
function modelOut(m: Partial<Record<UsageSource, UsageTotals>> | undefined, metric: Metric = 'out') {
  let out = 0;
  let req = 0;
  for (const t of Object.values(m ?? {})) {
    if (!t) continue;
    out += tokensOf(t, metric);
    req += t.requests;
  }
  return { out, req };
}

const WINDOWS = [
  { id: '24h', label: '24 hours' },
  { id: '7d', label: '7 days' },
  { id: '30d', label: '30 days' },
] as const;

function formatTokens(v: number) {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)}k`;
  return Math.round(v).toLocaleString();
}

function formatBucket(ts: string, bucketSeconds: number, long = false) {
  const d = new Date(ts);
  if (bucketSeconds >= 86_400) {
    return d.toLocaleDateString(undefined, { year: long ? 'numeric' : undefined, month: 'short', day: 'numeric' });
  }
  return long
    ? d.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
    : d.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
}

function sum(point: Pick<UsagePoint, 'sources'>, s: Series): UsageTotals {
  const out = { requests: 0, tokens_in: 0, tokens_out: 0 };
  for (const src of s.sources) {
    const t = point.sources[src];
    if (!t) continue;
    out.requests += t.requests;
    out.tokens_in += t.tokens_in;
    out.tokens_out += t.tokens_out;
  }
  return out;
}

interface UsageChartProps {
  /** Lifetime per-model earnings, the fallback ranking before `colours` arrives. */
  models?: ModelEarnings[];
  /** The earnings chart's colour map; used as-is so a model matches in both. */
  colours?: ModelColourMap | null;
}

export function UsageChart({ models, colours: shared }: UsageChartProps) {
  const [window_, setWindow] = useState<string>('24h');
  const [view, setView] = useState<'model' | 'source'>('model');
  const [metric, setMetric] = useState<Metric>('out');
  const [hovered, setHovered] = useState<number | null>(null);
  const { data, loading, error } = usePolling(
    useCallback(() => api.getUsageHistory(window_), [window_]),
    60_000,
  );

  const points = useMemo(() => data?.points ?? [], [data?.points]);
  const bucketSeconds = data?.bucket_seconds ?? 3600;

  // The window's per-model totals, for the readout when nothing is hovered.
  const windowModels = useMemo(() => {
    const acc: ModelsBySource = {};
    for (const p of points) {
      for (const [model, bySource] of Object.entries(p.models ?? {})) {
        const m = (acc[model] ??= {});
        for (const [src, t] of Object.entries(bySource)) {
          if (!t) continue;
          const cur = (m[src as UsageSource] ??= { requests: 0, tokens_in: 0, tokens_out: 0 });
          cur.requests += t.requests;
          cur.tokens_in += t.tokens_in;
          cur.tokens_out += t.tokens_out;
        }
      }
    }
    return acc;
  }, [points]);

  // Ranked on lifetime earnings like the earnings chart, so the same model is
  // the same colour in both. Models with usage but no earnings are appended at
  // zero, which keeps them eligible for a colour instead of vanishing.
  const own = useMemo(() => {
    const ranked = new Map<string, ModelEarnings>();
    for (const m of models ?? []) ranked.set(m.model, m);
    for (const id of Object.keys(windowModels)) {
      if (!ranked.has(id)) {
        ranked.set(id, { model: id, total_usd: 0, tokens_in: 0, tokens_out: 0, input_usd: 0, output_usd: 0, priced: false });
      }
    }
    return buildModelColours([...ranked.values()]);
  }, [models, windowModels]);
  const colours = shared ?? own;

  const segmentsFor = useCallback(
    (sources: UsagePoint['sources'], byModel: ModelsBySource): Segment[] => {
      if (view === 'source') {
        return SERIES.map((s) => {
          const t = sum({ sources }, s);
          return {
            key: s.key,
            colour: s.colour,
            value: tokensOf(t, metric),
            title: s.title,
            label: s.key === 'direct' && metric === 'in' ? `${s.label} (at least)` : s.label,
            detail:
              s.key === 'direct'
                ? 'requests not seen'
                : `${t.requests.toLocaleString()} req · ${formatTokens(metric === 'out' ? t.tokens_in : t.tokens_out)} ${metric === 'out' ? 'in' : 'out'}`,
          };
        });
      }
      const named: Segment[] = [];
      let other = 0;
      const otherSources: Partial<Record<UsageSource, UsageTotals>> = {};
      for (const [model, bySource] of Object.entries(byModel)) {
        const { out } = modelOut(bySource, metric);
        if (out <= 0) continue;
        if (colours.colours.has(model)) {
          named.push({ key: model, label: model, colour: colourFor(colours, model), value: out, detail: sourceBreakdown(bySource, metric) });
        } else {
          other += out;
          for (const [src, t] of Object.entries(bySource)) {
            if (!t) continue;
            const cur = (otherSources[src as UsageSource] ??= { requests: 0, tokens_in: 0, tokens_out: 0 });
            cur.tokens_out += t.tokens_out;
            cur.tokens_in += t.tokens_in;
          }
        }
      }
      named.sort((a, b) => b.value - a.value);
      if (other > 0) {
        named.push({ key: '__other', label: OTHER_LABEL, colour: OTHER_COLOUR, value: other, detail: sourceBreakdown(otherSources, metric) });
      }
      return named;
    },
    [view, colours, metric],
  );

  const peak = points.reduce((m, p) => Math.max(m, segmentsFor(p.sources, p.models ?? {}).reduce((a, s) => a + s.value, 0)), 0);
  const active = hovered !== null ? points[hovered] : null;
  const summarySegments = active
    ? segmentsFor(active.sources, active.models ?? {})
    : data
      ? segmentsFor(data.totals, windowModels)
      : [];
  // The legend names models that appear in this window, not every model ever.
  const legendModels = (() => {
    const present = new Set(Object.keys(windowModels).filter((m) => modelOut(windowModels[m], metric).out > 0));
    const entries: { key: string; label: string; colour: string; title?: string }[] = colours.ordered
      .filter((m) => present.has(m))
      .map((m) => ({ key: m, label: m, colour: colourFor(colours, m) }));
    if ([...present].some((m) => !colours.colours.has(m))) {
      entries.push({ key: '__other', label: OTHER_LABEL, colour: OTHER_COLOUR });
    }
    return entries;
  })();
  const summaryLabel = active
    ? formatBucket(active.timestamp, bucketSeconds, true)
    : (WINDOWS.find((w) => w.id === window_)?.label ?? window_);

  const unmeasured = (data?.endpoints ?? []).filter((e) => !e.measured);
  const hubOut = data ? tokensOf(sum({ sources: data.totals }, SERIES[0]), metric) : 0;
  const allOut = data ? SERIES.reduce((a, s) => a + tokensOf(sum({ sources: data.totals }, s), metric), 0) : 0;

  return (
    <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 px-4 py-3">
        <div>
          <h3 className="text-sm font-medium text-slate-300">Usage over time</h3>
          <p className="text-xs text-slate-400">
            {loading && !data
              ? 'Loading…'
              : allOut > 0
                ? `${formatTokens(allOut)} ${metric === 'out' ? 'tokens generated' : 'input tokens'} · ${Math.round((hubOut / allOut) * 100)}% for the hub`
                : 'No generated tokens in this window'}
          </p>
        </div>
        <div className="flex flex-wrap gap-1">
        <div className="flex gap-1" role="group" aria-label="Tokens measured">
          {(['out', 'in'] as const).map((m) => (
            <button
              key={m}
              type="button"
              onClick={() => setMetric(m)}
              aria-pressed={metric === m}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium transition focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                metric === m ? 'bg-slate-700 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'
              }`}
            >
              {m === 'out' ? 'Output' : 'Input'}
            </button>
          ))}
        </div>
        <div className="flex gap-1" role="group" aria-label="Split bars by">
          {(['model', 'source'] as const).map((v) => (
            <button
              key={v}
              type="button"
              onClick={() => setView(v)}
              aria-pressed={view === v}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium transition focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                view === v ? 'bg-slate-700 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'
              }`}
            >
              By {v}
            </button>
          ))}
        </div>
        <div className="flex gap-1" role="group" aria-label="Time window">
          {WINDOWS.map((w) => (
            <button
              key={w.id}
              type="button"
              onClick={() => setWindow(w.id)}
              aria-pressed={window_ === w.id}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium transition focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                window_ === w.id ? 'bg-slate-700 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'
              }`}
            >
              {w.label}
            </button>
          ))}
        </div>
        </div>
      </div>

      {error && !data ? (
        <p className="px-4 py-6 text-sm text-amber-300">Could not load usage: {error.message}</p>
      ) : points.length === 0 ? (
        <p className="px-4 py-6 text-sm text-slate-400">No usage recorded for this window yet.</p>
      ) : (
        <div className="px-4 py-4">
          <div className="mb-2 min-h-32 text-xs" aria-live="polite">
            <div className="flex items-baseline gap-2">
              <span className="text-slate-400">{summaryLabel}</span>
              {!active && <span className="text-slate-500">· hover a bar for one interval</span>}
            </div>
            {summarySegments.length > 0 ? (
              <ul className="mt-1 space-y-0.5 text-[11px]">
                {summarySegments.map((s) => (
                  <li key={s.key} title={s.title}>
                    <div className="flex items-center gap-2">
                      <span aria-hidden="true" className="h-2 w-2 shrink-0 rounded-sm" style={{ backgroundColor: s.colour }} />
                      <span className="min-w-0 flex-1 truncate text-slate-300">{s.label}</span>
                      <span className="shrink-0 font-mono text-slate-400">{formatTokens(s.value)} {metric}</span>
                    </div>
                    {/* Its own line: at half width, a right-aligned column cut
                        off the direct share, which is the part worth reading. */}
                    {s.detail && <div className="pl-4 font-mono text-[10px] text-slate-500">{s.detail}</div>}
                  </li>
                ))}
              </ul>
            ) : (
              <div className="mt-1 text-slate-500">Nothing generated.</div>
            )}
          </div>

          <div
            className="flex h-32 items-end gap-px"
            onMouseLeave={() => setHovered(null)}
            role="group"
            aria-label={`${metric === 'out' ? 'Generated' : 'Input'} tokens per interval over ${window_}, split by ${view}`}
          >
            {points.map((p, i) => {
              const segs = segmentsFor(p.sources, p.models ?? {}).filter((x) => x.value > 0);
              const total = segs.reduce((a, x) => a + x.value, 0);
              const h = peak > 0 && total > 0 ? Math.max(2, (total / peak) * 100) : 0;
              const describe = segs.length ? segs.map((x) => `${x.label} ${formatTokens(x.value)}`).join(', ') : 'nothing generated';
              return (
                <button
                  key={p.timestamp}
                  type="button"
                  onMouseEnter={() => setHovered(i)}
                  onFocus={() => setHovered(i)}
                  onBlur={() => setHovered(null)}
                  aria-label={`${formatBucket(p.timestamp, bucketSeconds, true)}: ${describe}`}
                  className={`flex h-full flex-1 flex-col justify-end focus:outline-none focus:ring-1 focus:ring-blue-400 ${hovered === i ? 'ring-1 ring-white/40' : ''}`}
                >
                  <span className="flex w-full flex-col-reverse" style={{ height: `${h}%` }}>
                    {segs.map((x, idx) => (
                      <span
                        key={x.key}
                        className={idx === segs.length - 1 ? 'block w-full rounded-t' : 'block w-full'}
                        style={{
                          height: `${(x.value / total) * 100}%`,
                          backgroundColor: x.colour,
                          marginTop: idx === segs.length - 1 ? 0 : 2,
                          opacity: hovered === i ? 1 : 0.85,
                        }}
                      />
                    ))}
                  </span>
                </button>
              );
            })}
          </div>

          <div className="mt-2 flex justify-between text-xs text-slate-400">
            <span>{points[0] && formatBucket(points[0].timestamp, bucketSeconds, true)}</span>
            <span>{points[points.length - 1] && formatBucket(points[points.length - 1].timestamp, bucketSeconds, true)}</span>
          </div>

          <ul className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs" aria-label={view === 'model' ? 'Models in this chart' : 'Sources in this chart'}>
            {(view === 'source' ? SERIES.map((s) => ({ key: s.key, label: s.label, colour: s.colour, title: s.title })) : legendModels).map((s) => (
              <li key={s.key} className="flex min-w-0 items-center gap-1.5" title={s.title}>
                <span aria-hidden="true" className="h-2 w-2 shrink-0 rounded-sm" style={{ backgroundColor: s.colour }} />
                <span className="break-all text-slate-400">{s.label}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex items-start gap-2 border-t border-slate-800 px-4 py-3 text-xs text-slate-400">
        <AlertCircle aria-hidden="true" size={14} className="mt-px shrink-0" />
        <div className="space-y-1">
          <p>
            {metric === 'out'
              ? 'Bars are generated tokens.'
              : 'Bars are input tokens. Direct input is a floor: the model server’s prompt counter skips cache hits, so the real figure can only be higher.'}{' '}
            Only hub traffic is paid.
            {data?.local_gateway && (
              <>
                {' '}Point local clients at <span className="font-mono text-slate-300">{data.local_gateway}</span> to
                record them as local rather than direct.
              </>
            )}
          </p>
          {unmeasured.length > 0 && (
            <p className="text-amber-300/90">
              Direct usage is not measured for{' '}
              {unmeasured.map((e, i) => (
                <span key={e.endpoint}>
                  {i > 0 && '; '}
                  <span className="break-all font-mono">{e.models.join(', ')}</span> ({e.reason})
                </span>
              ))}
              . Work sent straight to {unmeasured.length === 1 ? 'that server' : 'those servers'} is not shown.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
