import { useCallback, useMemo, useState } from 'react';
import { AlertCircle } from 'lucide-react';
import { api } from '../api/client';
import { usePolling } from '../hooks/usePolling';
import { OTHER_COLOUR, SERIES_COLOURS } from '../lib/modelPalette';
import type { UsagePoint, UsageSource, UsageTotals } from '../types';

/**
 * What the GPUs did, by where the work came from.
 *
 * The earnings chart says what was paid. This says what was served, so the
 * difference — the operator's own benchmarks, the node's probes, and work that
 * reached a model server without passing through the node — is visible rather
 * than being load nobody can account for.
 *
 * Bars measure generated tokens. That is the one figure every source has:
 * direct usage comes from a server's counters, which count tokens but not
 * requests, and prompt counters exclude cache hits so they cannot be compared.
 */

interface Series {
  key: string;
  label: string;
  colour: string;
  sources: UsageSource[];
  title: string;
}

// Colour carries meaning here, not identity: blue is the only paid series.
const SERIES: Series[] = [
  { key: 'hub', label: 'Hub (paid)', colour: SERIES_COLOURS[0], sources: ['hub'], title: 'Routed by Swan Inference — the only traffic that earns' },
  { key: 'local', label: 'Local gateway', colour: SERIES_COLOURS[1], sources: ['local'], title: 'Your own clients, sent through the node’s local gateway' },
  { key: 'direct', label: 'Direct to backend', colour: SERIES_COLOURS[2], sources: ['direct'], title: 'Generated by a model server without passing through the node' },
  { key: 'probes', label: 'Probes', colour: OTHER_COLOUR, sources: ['health', 'selfcheck'], title: 'This node’s own health and audit checks' },
];

const WINDOWS = [
  { id: '24h', label: '24 hours' },
  { id: '7d', label: '7 days' },
  { id: '30d', label: '30 days' },
] as const;

function formatTokens(v: number) {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)}k`;
  return Math.round(v).toLocaleString();
}

function formatBucket(ts: string, bucketSeconds: number, long = false) {
  const d = new Date(ts);
  if (bucketSeconds >= 86_400) {
    return d.toLocaleDateString(undefined, { year: long ? 'numeric' : undefined, month: 'short', day: 'numeric' });
  }
  return long
    ? d.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
    : d.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
}

function sum(point: Pick<UsagePoint, 'sources'>, s: Series): UsageTotals {
  const out = { requests: 0, tokens_in: 0, tokens_out: 0 };
  for (const src of s.sources) {
    const t = point.sources[src];
    if (!t) continue;
    out.requests += t.requests;
    out.tokens_in += t.tokens_in;
    out.tokens_out += t.tokens_out;
  }
  return out;
}

export function UsageChart() {
  const [window_, setWindow] = useState<string>('24h');
  const [hovered, setHovered] = useState<number | null>(null);
  const { data, loading, error } = usePolling(
    useCallback(() => api.getUsageHistory(window_), [window_]),
    60_000,
  );

  const points = useMemo(() => data?.points ?? [], [data?.points]);
  const bucketSeconds = data?.bucket_seconds ?? 3600;
  const peak = points.reduce(
    (m, p) => Math.max(m, SERIES.reduce((a, s) => a + sum(p, s).tokens_out, 0)),
    0,
  );
  const active = hovered !== null ? points[hovered] : null;
  const summary = active ?? (data ? { sources: data.totals } : null);
  const summaryLabel = active
    ? formatBucket(active.timestamp, bucketSeconds, true)
    : (WINDOWS.find((w) => w.id === window_)?.label ?? window_);

  const unmeasured = (data?.endpoints ?? []).filter((e) => !e.measured);
  const hubOut = data ? sum({ sources: data.totals }, SERIES[0]).tokens_out : 0;
  const allOut = data ? SERIES.reduce((a, s) => a + sum({ sources: data.totals }, s).tokens_out, 0) : 0;

  return (
    <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 px-4 py-3">
        <div>
          <h3 className="text-sm font-medium text-slate-300">Usage over time</h3>
          <p className="text-xs text-slate-400">
            {loading && !data
              ? 'Loading…'
              : allOut > 0
                ? `${formatTokens(allOut)} tokens generated · ${Math.round((hubOut / allOut) * 100)}% for the hub`
                : 'No generated tokens in this window'}
          </p>
        </div>
        <div className="flex gap-1" role="group" aria-label="Time window">
          {WINDOWS.map((w) => (
            <button
              key={w.id}
              type="button"
              onClick={() => setWindow(w.id)}
              aria-pressed={window_ === w.id}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium transition focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                window_ === w.id ? 'bg-slate-700 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'
              }`}
            >
              {w.label}
            </button>
          ))}
        </div>
      </div>

      {error && !data ? (
        <p className="px-4 py-6 text-sm text-amber-300">Could not load usage: {error.message}</p>
      ) : points.length === 0 ? (
        <p className="px-4 py-6 text-sm text-slate-400">No usage recorded for this window yet.</p>
      ) : (
        <div className="px-4 py-4">
          <div className="mb-2 min-h-24 text-xs" aria-live="polite">
            <div className="flex items-baseline gap-2">
              <span className="text-slate-400">{summaryLabel}</span>
              {!active && <span className="text-slate-500">· hover a bar for one interval</span>}
            </div>
            {summary && (
              <ul className="mt-1 space-y-0.5 text-[11px]">
                {SERIES.map((s) => {
                  const t = sum(summary, s);
                  return (
                    <li key={s.key} className="flex items-center gap-2" title={s.title}>
                      <span aria-hidden="true" className="h-2 w-2 shrink-0 rounded-sm" style={{ backgroundColor: s.colour }} />
                      <span className="min-w-0 flex-1 truncate text-slate-300">{s.label}</span>
                      <span className="font-mono text-slate-400">{formatTokens(t.tokens_out)} out</span>
                      <span className="w-40 shrink-0 whitespace-nowrap text-right font-mono text-slate-500">
                        {s.key === 'direct' ? 'requests not seen' : `${t.requests.toLocaleString()} req · ${formatTokens(t.tokens_in)} in`}
                      </span>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>

          <div
            className="flex h-32 items-end gap-px"
            onMouseLeave={() => setHovered(null)}
            role="group"
            aria-label={`Generated tokens per interval over ${window_}, split by source`}
          >
            {points.map((p, i) => {
              const segs = SERIES.map((s) => ({ s, v: sum(p, s).tokens_out })).filter((x) => x.v > 0);
              const total = segs.reduce((a, x) => a + x.v, 0);
              const h = peak > 0 && total > 0 ? Math.max(2, (total / peak) * 100) : 0;
              const describe = segs.length ? segs.map((x) => `${x.s.label} ${formatTokens(x.v)}`).join(', ') : 'nothing generated';
              return (
                <button
                  key={p.timestamp}
                  type="button"
                  onMouseEnter={() => setHovered(i)}
                  onFocus={() => setHovered(i)}
                  onBlur={() => setHovered(null)}
                  aria-label={`${formatBucket(p.timestamp, bucketSeconds, true)}: ${describe}`}
                  className={`flex h-full flex-1 flex-col justify-end focus:outline-none focus:ring-1 focus:ring-blue-400 ${hovered === i ? 'ring-1 ring-white/40' : ''}`}
                >
                  <span className="flex w-full flex-col-reverse" style={{ height: `${h}%` }}>
                    {segs.map((x, idx) => (
                      <span
                        key={x.s.key}
                        className={idx === segs.length - 1 ? 'block w-full rounded-t' : 'block w-full'}
                        style={{
                          height: `${(x.v / total) * 100}%`,
                          backgroundColor: x.s.colour,
                          marginTop: idx === segs.length - 1 ? 0 : 2,
                          opacity: hovered === i ? 1 : 0.85,
                        }}
                      />
                    ))}
                  </span>
                </button>
              );
            })}
          </div>

          <div className="mt-2 flex justify-between text-xs text-slate-400">
            <span>{points[0] && formatBucket(points[0].timestamp, bucketSeconds, true)}</span>
            <span>{points[points.length - 1] && formatBucket(points[points.length - 1].timestamp, bucketSeconds, true)}</span>
          </div>

          <ul className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs" aria-label="Sources in this chart">
            {SERIES.map((s) => (
              <li key={s.key} className="flex items-center gap-1.5" title={s.title}>
                <span aria-hidden="true" className="h-2 w-2 shrink-0 rounded-sm" style={{ backgroundColor: s.colour }} />
                <span className="text-slate-400">{s.label}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex items-start gap-2 border-t border-slate-800 px-4 py-3 text-xs text-slate-400">
        <AlertCircle aria-hidden="true" size={14} className="mt-px shrink-0" />
        <div className="space-y-1">
          <p>
            Bars are generated tokens. Only hub traffic is paid.
            {data?.local_gateway && (
              <>
                {' '}Point local clients at <span className="font-mono text-slate-300">{data.local_gateway}</span> to
                record them as local rather than direct.
              </>
            )}
          </p>
          {unmeasured.length > 0 && (
            <p className="text-amber-300/90">
              Direct usage is not measured for{' '}
              {unmeasured.map((e, i) => (
                <span key={e.endpoint}>
                  {i > 0 && '; '}
                  <span className="break-all font-mono">{e.models.join(', ')}</span> ({e.reason})
                </span>
              ))}
              . Work sent straight to {unmeasured.length === 1 ? 'that server' : 'those servers'} is not shown.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
