package modelmem

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// NodeContext is what the agent needs to know about the machine it is
// operating, beyond the models themselves.
type NodeContext struct {
	NodeName     string
	NodeID       string
	GPUModel     string
	GPUCount     int
	VRAMPerGPUGB int
	TotalVRAMGB  int
	Serving      []string
}

// Markdown renders cp.md: the operating context for an agent running this node.
//
// Written for an agent to read, which shapes it in three ways. It states what
// is true rather than what is nice to know, because every line costs context.
// It gives reproduction commands rather than descriptions, because an agent
// acts by running things. And it is explicit about what must not be done, since
// an agent has no operator watching it decide.
//
// Generated and never parsed back, so the store remains the single source of
// truth and this cannot drift from it.
func (s *Store) Markdown(node NodeContext) string {
	var b strings.Builder

	b.WriteString("# cp.md — operating context for this node\n\n")
	b.WriteString("Generated by `computing-provider`. **Do not edit**: it is rewritten from\n")
	b.WriteString("`" + StoreFile + "` on every change and edits here are lost. Change a record\n")
	b.WriteString("with `computing-provider models memory`.\n\n")

	writeNode(&b, node)
	writeRules(&b)
	s.writeMemory(&b)
	writeCommands(&b)

	return b.String()
}

func writeNode(b *strings.Builder, n NodeContext) {
	b.WriteString("## This node\n\n")
	if n.NodeName != "" {
		b.WriteString(fmt.Sprintf("- **Name:** %s\n", n.NodeName))
	}
	if n.NodeID != "" {
		// Abbreviated: the full identifier is 129 characters and nothing an
		// agent does needs it, while every line here costs context.
		b.WriteString(fmt.Sprintf("- **ID:** `%s…`\n", shorten(n.NodeID, 24)))
	}
	if n.GPUCount > 0 {
		b.WriteString(fmt.Sprintf("- **GPUs:** %d× %s, %d GB each, **%d GB total**\n",
			n.GPUCount, n.GPUModel, n.VRAMPerGPUGB, n.TotalVRAMGB))
		b.WriteString(fmt.Sprintf("  - A model must fit in %d GB *including* KV cache and ~1 GB of\n", n.TotalVRAMGB))
		b.WriteString("    CUDA overhead, and must shard across the cards to use more than\n")
		b.WriteString(fmt.Sprintf("    %d GB. A single tensor that does not shard is capped there.\n", n.VRAMPerGPUGB))
	}
	if len(n.Serving) > 0 {
		b.WriteString(fmt.Sprintf("- **Serving now:** %s\n", strings.Join(n.Serving, ", ")))
	}
	b.WriteString("\n")
}

func writeRules(b *strings.Builder) {
	b.WriteString("## Rules\n\n")
	b.WriteString("These are enforced in code as well as stated here. An agent that ignores\n")
	b.WriteString("them will be refused, but knowing them avoids wasting a cycle proposing\n")
	b.WriteString("something that cannot happen.\n\n")
	b.WriteString("1. **Only containers `computing-provider` started can be stopped.** A backend\n")
	b.WriteString("   the operator started by hand is not yours to touch. `models ps` lists what\n")
	b.WriteString("   is yours.\n")
	b.WriteString("2. **A model with no known VRAM requirement cannot be served.** Unknown is a\n")
	b.WriteString("   refusal, not a zero. Measured beats derived; derived beats published;\n")
	b.WriteString("   nothing beats nothing.\n")
	b.WriteString("3. **Never plan on weight size alone.** It under-predicts real usage by\n")
	b.WriteString("   roughly 20%; the KV cache and CUDA overhead are not rounding errors.\n")
	b.WriteString("4. **The planner model is pinned** and must never be stopped — stopping it\n")
	b.WriteString("   leaves no planner for the next decision.\n")
	b.WriteString("5. **Weights are never downloaded automatically.** A model with no local\n")
	b.WriteString("   weights is reported, not fetched.\n\n")
}

func (s *Store) writeMemory(b *strings.Builder) {
	records := s.All()

	b.WriteString("## Models this node has run\n\n")
	if len(records) == 0 {
		b.WriteString("Nothing recorded yet. This fills in as models are served.\n\n")
		return
	}

	b.WriteString("Measured here, on this hardware, with the settings shown. **Where a figure\n")
	b.WriteString("here disagrees with an estimate derived from published metadata, this one\n")
	b.WriteString("is right.** Published metadata describes the original weights; these are\n")
	b.WriteString("what the node actually loaded.\n\n")

	working, failed := split(records)

	if len(working) > 0 {
		b.WriteString("### Known to work\n\n")
		b.WriteString("| model | measured | weights | context |\n|---|---|---|---|\n")
		for _, r := range working {
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",
				r.ModelID, vramCell(r), weightsCell(r), ctxCell(r)))
		}
		b.WriteString("\n")
		for _, r := range working {
			writeDetail(b, r)
		}
	}

	if len(failed) > 0 {
		b.WriteString("### Known not to work\n\n")
		b.WriteString("Do not retry these blindly. The note says what went wrong, which is the\n")
		b.WriteString("difference between never trying again and trying correctly.\n\n")
		for _, r := range failed {
			b.WriteString(fmt.Sprintf("- **`%s`** — %s", r.ModelID, orDash(r.Note)))
			if r.Failures > 0 {
				b.WriteString(fmt.Sprintf(" _(%d failed %s)_", r.Failures, plural(r.Failures, "start", "starts")))
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
}

// writeDetail renders one model, ending in the command that reproduces it.
func writeDetail(b *strings.Builder, r *Record) {
	b.WriteString(fmt.Sprintf("#### `%s`\n\n", r.ModelID))

	if r.Pinned {
		b.WriteString("_Pinned by the operator. Automatic runs will not overwrite this record._\n\n")
	}
	if r.Note != "" {
		b.WriteString(r.Note + "\n\n")
	}

	if r.Measured != nil {
		b.WriteString(fmt.Sprintf("- Measured **%.2f GiB**", r.Measured.VRAMGiB))
		if len(r.Measured.PerGPUGiB) > 1 {
			parts := make([]string, 0, len(r.Measured.PerGPUGiB))
			for _, v := range r.Measured.PerGPUGiB {
				parts = append(parts, fmt.Sprintf("%.2f", v))
			}
			b.WriteString(fmt.Sprintf(" across %d GPUs (%s GiB)",
				len(r.Measured.PerGPUGiB), strings.Join(parts, " + ")))
		}
		b.WriteString(fmt.Sprintf(", %s\n", r.Measured.At.UTC().Format("2006-01-02")))
	}
	if r.Weights.LocalPath != "" {
		b.WriteString(fmt.Sprintf("- Weights on disk: `%s`\n", r.Weights.LocalPath))
	}
	if r.Weights.Repo != "" {
		b.WriteString(fmt.Sprintf("- Source: `%s`", r.Weights.Repo))
		if r.Weights.Revision != "" {
			b.WriteString(fmt.Sprintf(" at `%s`", r.Weights.Revision))
		}
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf("- Runs: %d successful", r.Successes))
	if r.Failures > 0 {
		b.WriteString(fmt.Sprintf(", %d failed", r.Failures))
	}
	b.WriteString(fmt.Sprintf(", last %s\n\n", humanSince(r.LastSeen)))

	if cmd := ReproduceCommand(r); cmd != "" {
		b.WriteString("Reproduce with:\n\n```bash\n" + cmd + "\n```\n\n")
	}
}

// ReproduceCommand renders the `models serve` invocation that produced this
// record.
//
// The most useful thing the memory holds: an agent re-serving a known-good
// model should run what worked rather than reconstruct it from fields and get
// one flag wrong.
func ReproduceCommand(r *Record) string {
	if r == nil || !r.Works() || r.Serving.Backend == "" || r.Weights.LocalPath == "" {
		return ""
	}

	parts := []string{
		"computing-provider models serve",
		"--backend " + r.Serving.Backend,
		"--weights " + r.Weights.LocalPath,
	}
	if r.Serving.GPUs != "" {
		parts = append(parts, "--gpus "+r.Serving.GPUs)
	}
	if r.Serving.ContextLength > 0 {
		parts = append(parts, fmt.Sprintf("--context-length %d", r.Serving.ContextLength))
	}
	if r.Serving.Image != "" {
		parts = append(parts, "--image "+r.Serving.Image)
	}
	if v := r.VRAMGiB(); v > 0 {
		parts = append(parts, fmt.Sprintf("--gpu-memory %d", int(v*1024)))
	}
	parts = append(parts, r.ModelID)

	// Passthrough arguments go on one line: they are flag/value pairs for
	// the inference server, and splitting them across continuations makes a
	// copied command read as though each word were a separate flag.
	if len(r.Serving.ExtraArgs) > 0 {
		parts = append(parts, strings.Join(r.Serving.ExtraArgs, " "))
	}

	return strings.Join(parts, " \\\n  ")
}

func writeCommands(b *strings.Builder) {
	b.WriteString("## Commands available\n\n")
	b.WriteString("```bash\n")
	b.WriteString("computing-provider models ps                 # what this tool is running\n")
	b.WriteString("computing-provider models serve <id> ...     # start and declare a model\n")
	b.WriteString("computing-provider models stop <id>          # stop and stop declaring it\n")
	b.WriteString("computing-provider models list               # weights already on disk\n")
	b.WriteString("computing-provider models memory             # this file's underlying records\n")
	b.WriteString("computing-provider inference plan            # one planning cycle, changes nothing\n")
	b.WriteString("computing-provider inference recommend-models\n")
	b.WriteString("```\n\n")
	b.WriteString("Flags come before the model ID; anything after it is passed to the\n")
	b.WriteString("inference server, as `docker run [options] IMAGE [command]` does.\n")
}

func split(records []*Record) (working, failed []*Record) {
	for _, r := range records {
		if r.Works() {
			working = append(working, r)
		} else {
			failed = append(failed, r)
		}
	}
	// Largest first: an agent looking for something that fits reads down.
	sort.SliceStable(working, func(i, j int) bool { return working[i].VRAMGiB() > working[j].VRAMGiB() })
	return working, failed
}

func vramCell(r *Record) string {
	if v := r.VRAMGiB(); v > 0 {
		return fmt.Sprintf("**%.1f GiB**", v)
	}
	return "not measured"
}

func weightsCell(r *Record) string {
	var parts []string
	if r.Weights.Repo != "" {
		parts = append(parts, "`"+r.Weights.Repo+"`")
	} else if r.Weights.URL != "" {
		parts = append(parts, r.Weights.URL)
	}
	if r.Weights.Quantisation != "" {
		parts = append(parts, r.Weights.Quantisation)
	} else if r.Weights.Format != "" {
		parts = append(parts, r.Weights.Format)
	}
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, " · ")
}

func ctxCell(r *Record) string {
	if r.Serving.ContextLength > 0 {
		return fmt.Sprintf("%d", r.Serving.ContextLength)
	}
	return "—"
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return s
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

func humanSince(t time.Time) string {
	if t.IsZero() {
		return "never"
	}
	return t.UTC().Format("2006-01-02 15:04 MST")
}

// shorten truncates an identifier for display.
func shorten(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
